components/forms/NewJobForm.tsx

| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/72622d6b-b8f8-44c8-b4ca-7430482f45a7) | ![image](https://github.com/user-attachments/assets/ba508764-128e-453f-812e-8586d006d2e4) |

fix: update placeholder text for company salary input in NewJobForm

---

README.md
components/Navbar/Navbar.tsx
components/UserImage.tsx

I have used the Shadcn dropdown menu to fix the problem where the login button remains visible after logging. The dropdown menu now displays user information, including the user's profile image, email, name, and a logout button.
https://github.com/user-attachments/assets/5ab6b1d8-0091-4913-b469-ceded4b3fa95

Profile dropdown button created

---

components/forms/LoginForm.tsx
zod/user.ts

Fixes #48 
- Design improvements can be made as per the requirements. This PR fixes the validation and logic issues with react-hook-form and zod resolver to main consistency throughout the project. 
- Any UI changes can be made to this pr without changing the underlying core logic which uses react-hook-from for validations and form submissions.
- Here is the new login form: 
- Error States: 
- The error states are handled through <FormMessage /> controllers that handles the errors, reducing the need of any further states and toast messages. Toast messages are used on form submissions.
- If anyone wants to further add input validation and new rules, they can simply modify the zod schema for user login form.

[FIX]: Login form validation with react-hook-form

---

.env.example
Dockerfile
README.md
auth.ts
docker-compose.yml
prisma/seed.ts

[feat]: add docker file
Fixes #27

adds dockerfile

---

app/(auth)/layout.tsx
app/(protected)/jobs/layout.tsx
app/layout.tsx
app/page.tsx
components/Footer.tsx

- Fixed `<Footer/>` positioning everywhere.
- Fixed `s` getting cut at Home page.
https://github.com/user-attachments/assets/6c77bb67-f7d8-4502-80ff-048808365740

Fix Footer positioning everywhere

---

app/(protected)/jobs/layout.tsx
app/(protected)/jobs/page.tsx
components/Sidebar.tsx

fix #112 
This PR fixes the minor padding issue in the mobile UI
Before:
After:

Fix/padding issue MobileNav

---

components/Navbar/Navbar.tsx

Fix : #124 
Demo: 
https://github.com/user-attachments/assets/be7b6560-82da-48c0-be63-475ee8078d7a

fix: Navbar alignment and tab hover color

---

components/forms/LoginForm.tsx

Added useRef hook which will auto focus on the email when login page opens

Added functionality to auto-focus on email when login page opens

---

src/components/all-jobs.tsx

Added Location in Job Listings #232

Added Location in Job listings #232

---

src/app/[...404]/page.tsx

#177 and #186 commit . @VineeTagarwaL-code  I did rebuild also and it works for me now. Check once and let me know if you find any

Created a 404 custom page

---

src/components/job-form.tsx

Fixes wrong placeholders in location and min salary and max salary in /create page

FIX : fixes wrong placeholder in /create page

---

src/components/navitem.tsx

corrected bracket formatting Fixed:#270

---

package.json
src/app/layout.tsx
src/components/Toploader.tsx

A top loader component has been added for better UX during page-navigation.
Requesting for review @hkirat @VineeTagarwaL-code @SwetanshuSingh

feat: Toploader component for better page-load UX

---

src/app/layout.tsx
src/components/ScrollToTop.tsx
src/components/job-landing.tsx
src/layouts/header.tsx

fixes #296 
https://github.com/user-attachments/assets/9a63c63d-61e6-4b18-ad72-73b0c3e84c2f

added scroll-top feature and navbar feature

---

package.json
src/app/[...404]/page.tsx

closes #302 
Fixed the Ui and tailwind issues for the error 404 page , it now looks like - 
@VineeTagarwaL-code  kindly merge .

fixed the error page UI

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/improvement.yml
src/app/editDetails/page.tsx
src/components/userDetails.tsx
src/lib/constant/app.constant.ts

Added UI for update Details page

---

src/components/all-jobs.tsx
src/components/ui/card.tsx

This covers:- #290
Before :- 
https://github.com/user-attachments/assets/f94644c1-53dd-4a43-bf1c-f21b4e36a04d
After:-
https://github.com/user-attachments/assets/6c7a35cc-e77c-4871-a8b8-eb0d6b94d306
Additional information:-
Used Shadcn UI for card

feat:explore job page improvement

---

src/layouts/header.tsx

fix- #332 
https://github.com/user-attachments/assets/06e7636e-d09f-42a7-a05b-8c9bbf6d2992

fix(#332)/responsive header on md screens

---

.github/workflows/ci.yaml
src/hooks/useSetQueryParams.ts

added a format stage before checking

debounce time + prettier format

---

src/app/admin/page.tsx
src/components/UserCard.tsx

This PR adds a UserCard component to display user profiles with key details such as name, title, skills, salary, and bio.
It also includes links to social profiles (GitHub, Twitter, LinkedIn) and a resume.

Create UserCard Component for Admin-Hr-dashboard

---

src/app/jobs/[id]/loading.tsx
src/app/jobs/loading.tsx
src/app/layout.tsx
src/components/JobcardSkeleton.tsx

fixes #355 
- added loaders
- removed top spinner

added-skeleton

---

src/app/page.tsx
src/components/TestimonialCard.tsx
src/components/Testimonials.tsx
src/config/path.config.ts
src/lib/constant/app.constant.ts
src/lib/constant/testimonials.constants.ts
src/types/testimonials.types.ts

https://github.com/user-attachments/assets/09d52360-5be9-498c-858b-80da27460399
It’s built based on the initial thoughts, but please let me know if it requires any further changes or improvements.

feat: Added testimonial section

---

src/app/globals.css
src/components/DescriptionEditor.tsx

This fixes PR #381
https://github.com/user-attachments/assets/a6986865-86f3-4a5a-a925-163d87798458
(ps: video is compressed)

ISSUE #381 - fixed react quill width

---

src/components/job-form.tsx

Issue resolved is:- https://github.com/code100x/job-board/issues/395

Added margin to improve spacing between the payment section and footer.

---

src/components/job-form.tsx

#What does this PR will do
This PR will add the margin between payment section and footer
Fixes #395

fix: margin issue between payment section and footer

---

src/config/path.config.ts
src/lib/constant/app.constant.ts

fixes: #429
Added logic to open mail when clicking on contact us as instructed.

Contact us link to open mail

---

src/app/jobs/loading.tsx
src/components/JobcardSkeleton.tsx

https://github.com/user-attachments/assets/89590726-0100-41e7-a561-eb89667711dc
- #438

feat: added loaders

---

src/services/jobs.services.ts

Fixes #447 
Change: Added the missing EmpType filter
Final look:
https://github.com/user-attachments/assets/6f8228f1-ca0b-4b23-94a2-3098a234b690

Fix: Employment type filter for job search (#447)

---

src/components/Jobcard.tsx
src/components/job-card.tsx
src/components/ui/accordion.tsx
src/layouts/job-filters.tsx

Fixed the following issues (#452 ) :
1. Removed scrollbars in job cards 
2. Icons shown for undisclosed experience and salary
3. Fixed text formatting for recommended job cards
4. Removed separator for last filter in job filters
5. More engaging filter text and checkbox
Additional change:
Fixed the image crop issue when the window size is small
Issue:
Fix:

Minor UI fixes

---

package.json
prisma/seed.ts
tsconfig.json

issue:- #444 
solved the issue , it is running smoothly now 
can give preference to @apsinghdev as he is assigned

Fixed database seeding script 

---

src/app/globals.css
src/components/DescriptionEditor.tsx
src/components/auth/signup.tsx
src/components/job-card.tsx
src/components/job-form.tsx
src/components/job.tsx
src/components/pagination-client.tsx

Changes  (#461):
- Improved tooltip visibility and fixed horizontal scroll for React Quill components
- Added a 'X' button to clear selected company logo
https://github.com/user-attachments/assets/92b65059-43cd-4e44-a2ac-97ee2b8a44fc
- Fixed light mode coloring scheme and salary range text formatting for job components
- Added styles for disabled pagination buttons
- Fixed minor typos

UI Improvements and fixes

---

src/components/Testimonials.tsx

fix: #464 
fixed overflow issue for mobile screens
@VineeTagarwaL-code  
https://github.com/user-attachments/assets/b529eb4e-a54a-44aa-801c-4a550a3f7c26

fix:overflow issue

---

prisma/schema.prisma
prisma/seed.ts
src/components/navitem.tsx
src/config/app.config.ts
src/layouts/header.tsx
src/layouts/mobile-nav.tsx
src/lib/constant/app.constant.ts
src/middleware.tsx

Feat: #463 
Added HR role.Hr can login and create new jobs.
HR credentails:
```  
hr@gmail.com
123456
```

feature:Added HR role

---

src/app/globals.css
src/components/ui/infinite-moving-cards.tsx

Fix: Inconsistent height in Card component (#465)

---

src/layouts/job-filters.tsx

Change (#471): Added the "Clear Filters" option and slightly improved design according to the figma design 
https://github.com/user-attachments/assets/de2a094c-1bee-4662-be3c-b22f041db4ad
Reference (Figma):

Added Clear filters option + UI fixes (#471)

---

src/lib/validators/jobs.validator.ts

fixes job-form submission which was bugged due to validation

fix:job-form-submission

---

src/hooks/useFilterCheck.ts
src/layouts/job-filters.tsx

feat: conditionally render Clear Filters button based on filter selection
Closes #488

feat: conditionally render Clear Filters button

---

prisma/migrations/20241015192257_added_cascading_job/migration.sql
prisma/schema.prisma
src/actions/user.profile.actions.ts

Fixed the account deletion option .. closes #507

FIX: fixed the bug of account deletion

---

src/components/job-form.tsx

fix: #514 
@VineeTagarwaL-code 
https://github.com/user-attachments/assets/58f316b8-c350-4250-b4c1-9718be7f3752

fix:create job page ui fix for mobile screen

---

src/components/ui/infinite-moving-cards.tsx

https://github.com/user-attachments/assets/565cc594-bf87-40d4-a5d9-8b804811dbde

Feat/Added drag-to-scroll functionality for Testimonials section

---

src/components/auth/signin.tsx

#561 bug-Added apt. toast message
